### ISSUE TITLE
Not able to run the tests

### ISSUE THREAD

**Issue by bittergeek** [jwood803/ElectronSpectronDemo#1]
I had to change const to var for:
`    const app;`
Then I got error running the tests: 

```
 Test Example
    1) "before each" hook for "opens a window"
    2) "after each" hook for "opens a window"


  0 passing (2s)
  2 failing

  1) Test Example "before each" hook for "opens a window":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  2) Test Example "after each" hook for "opens a window":
     Error: Application not running
      at Error (native)
      at Application.stop (node_modules\spectron\lib\application.js:56:48)
      at Context.<anonymous> (tests\test.js:35:18)
```

**Comment by bittergeek** [comment]
OK. The timeout is resolved by adding this:
this.timeout(15000);

**Comment by bittergeek** [comment]
And, I think the promise needs to be returned too?

```
it('opens a window', function () {
    page.getWindowCount().should.eventually.equal(page.windowCount);
  });

```

**Comment by jwood803** [comment]
That `done()` thing always trips me up. Got these working or still need some help?

**Comment by jwood803** [comment]
@bittergeek Just pushed 016dc4de07bcb7b3b7c1ab1ddb4a6e41b7b693cc that should fix the issues. Thanks for pointing this out!

Using `chai-as-promised` should resolve the promises in the actual tests. At least that's what the [mocha docs say](https://mochajs.org/#working-with-promises).

Feel free to let me know if any other issues arise.

**Comment by michaelnoinc** [comment]
With either the master or 016dc4d branch, I'm having the exact same issue. 

Except I have to change const app to var app in the more recent one otherwise I get this:

tests\test.page.js:2
    const app;
          ^^^

SyntaxError: Missing initializer in const declaration


Afterward I get this:

  Test Example
    1) "before each" hook for "opens a window"
(node:12960) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Application not running
(node:12960) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    2) "after each" hook for "opens a window"


  0 passing (4s)
  2 failing

  1) Test Example "before each" hook for "opens a window":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  2) Test Example "after each" hook for "opens a window":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
